#!/usr/bin/env python3
# Simple Calculator
num1 = 10
num2 = 5

sum_result = num1 + num2
difference = num1 - num2
product = num1 * num2
division = num1 / num2

print("First Number:", num1)
print("Second Number:", num2)

print("Addition:", sum_result)
print("Subtraction:", difference)
print("Multiplication:", product)
print("Division:", division)
